import { existsSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { afterAll, describe, expect, it } from 'vitest';
import { makeTempDir, runCli, write } from './helpers.js';

const dirs: string[] = [];
function tmp(prefix = 'cli-gen'): string {
  const dir = makeTempDir(prefix);
  dirs.push(dir);
  return dir;
}
afterAll(() => {
  for (const dir of dirs) rmSync(dir, { recursive: true, force: true });
});

const SPEC = JSON.stringify({
  name: 'Coupon Redemption',
  description: 'Users redeem coupons at checkout',
  acceptanceCriteria: [
    'A coupon with a maximum discount limit applies at most the limit',
    'An expired coupon must be rejected',
  ],
  businessRules: ['discounts never stack'],
  area: 'payment',
}, null, 2);

describe('generate command', () => {
  it('--dry-run lists would-write files without touching the disk', async () => {
    const root = tmp();
    write(root, 'coupon.json', SPEC);
    const res = await runCli(['generate', '--spec', 'coupon.json', '--dry-run', '--json'], root);
    expect(res.code).toBe(0);
    const data = res.json<{ label: string; data: { dryRun: boolean; files: Array<{ path: string; action: string; bytes: number }>; plan: { total: number; byCategory: Record<string, number>; byLayer: Record<string, number> }; heuristicNotes: string[] } }>().data;
    expect(res.json<{ label: string }>().label).toBe('NOT_RUN');
    expect(data.dryRun).toBe(true);
    expect(data.files.length).toBeGreaterThanOrEqual(1);
    expect(data.files.every((f) => f.action === 'dry-run')).toBe(true);
    expect(data.files[0]?.bytes).toBeGreaterThan(0);
    expect(existsSync(join(root, 'tests', 'generated'))).toBe(false);
    // payment area → security cases + critical priority; negative + boundary present
    expect(data.plan.byCategory['positive']).toBeGreaterThan(0);
    expect(data.plan.byCategory['negative']).toBeGreaterThan(0);
    expect(data.plan.byCategory['security']).toBeGreaterThan(0);
    expect(data.heuristicNotes.join(' ')).toMatch(/security: fired/);
  });

  it('writes scaffold files, then refuses overwrite without --force (skipped)', async () => {
    const root = tmp();
    write(root, 'coupon.json', SPEC);
    const first = await runCli(['generate', '--spec', 'coupon.json', '--json'], root);
    expect(first.code).toBe(0);
    const created = first.json<{ data: { files: Array<{ path: string; action: string }> } }>().data.files;
    expect(created.every((f) => f.action === 'created')).toBe(true);
    const written = created[0]?.path ?? '';
    expect(existsSync(written)).toBe(true);
    const content = readFileSync(written, 'utf8');
    expect(content).toContain('it.skip');
    expect(content).toContain('generated by @the-qa-skill/agents GenerationAgent');

    const second = await runCli(['generate', '--spec', 'coupon.json', '--json'], root);
    expect(second.code).toBe(0);
    const skipped = second.json<{ data: { files: Array<{ action: string }> } }>().data.files;
    expect(skipped.every((f) => f.action === 'skipped')).toBe(true);
  });

  it('respects --out and --force', async () => {
    const root = tmp();
    write(root, 'coupon.json', SPEC);
    await runCli(['generate', '--spec', 'coupon.json', '--out', 'gen/x', '--json'], root);
    expect(existsSync(join(root, 'gen', 'x', 'coupon-redemption.generated.test.ts'))).toBe(true);
    const forced = await runCli(['generate', '--spec', 'coupon.json', '--out', 'gen/x', '--force', '--json'], root);
    expect(forced.json<{ data: { files: Array<{ action: string }> } }>().data.files.every((f) => f.action === 'created')).toBe(true);
  });

  it('usage errors: missing --spec, missing file, invalid area (exit 2)', async () => {
    const root = tmp();
    const noSpec = await runCli(['generate', '--json'], root);
    expect(noSpec.code).toBe(2);
    expect(noSpec.json<{ data: { error: string } }>().data.error).toMatch(/--spec/);

    const missing = await runCli(['generate', '--spec', 'nope.json', '--json'], root);
    expect(missing.code).toBe(2);
    expect(missing.json<{ data: { error: string } }>().data.error).toMatch(/does not exist/);

    write(root, 'bad.json', JSON.stringify({ name: 'x', acceptanceCriteria: [], area: 'nope' }));
    const bad = await runCli(['generate', '--spec', 'bad.json', '--json'], root);
    expect(bad.code).toBe(2);
    expect(bad.json<{ data: { error: string } }>().data.error).toMatch(/"area"/);

    write(root, 'nocriteria.json', JSON.stringify({ name: 'x' }));
    const noCrit = await runCli(['generate', '--spec', 'nocriteria.json', '--json'], root);
    expect(noCrit.code).toBe(2);
  });
});

describe('review command', () => {
  it('flags a waitForTimeout file (determinism deduction) and reports suite health', async () => {
    const root = tmp();
    write(root, 'tests/bad.spec.ts', [
      "import { test, expect } from '@playwright/test';",
      "test('waits', async ({ page }) => {",
      "  await page.goto('http://localhost:3000');",
      '  await page.waitForTimeout(1000);',
      "  await expect(page.locator('#x')).toBeVisible();",
      '});',
      '',
    ].join('\n'));
    const res = await runCli(['review', 'tests/bad.spec.ts', '--json'], root);
    expect(res.code).toBe(0);
    const data = res.json<{ data: { reports: Array<{ filePath: string; score: number; testCount: number; deductions: Array<{ dimension: string; points: number; reason: string }> }>; suiteHealth: { score: number; components: unknown[] } } }>().data;
    const report = data.reports[0];
    expect(report?.filePath).toBe('tests/bad.spec.ts');
    const det = report?.deductions.find((d) => d.dimension === 'determinism');
    expect(det).toBeDefined();
    expect(det?.reason).toMatch(/arbitrary sleep|golden rule 3/i);
    expect(report?.testCount).toBe(1);
    expect(report?.score).toBeLessThan(100);
    expect(data.suiteHealth.components.length).toBe(10);
    expect(data.suiteHealth.score).toBeGreaterThanOrEqual(0);
  });

  it('discovers test-shaped files when no paths are given', async () => {
    const root = tmp();
    write(root, 'tests/a.test.ts', "import { test, expect } from 'vitest';\ntest('a', () => { expect(1).toBe(1); });\n");
    const res = await runCli(['review', '--json'], root);
    expect(res.code).toBe(0);
    expect(res.json<{ data: { reports: unknown[] } }>().data.reports.length).toBe(1);
  });
});

describe('test command', () => {
  it('--dry-run plans commands and spawns nothing (label NOT_RUN)', async () => {
    const root = tmp();
    write(root, 'package.json', JSON.stringify({ name: 'app', private: true, devDependencies: { vitest: '^2' } }, null, 2));
    write(root, 'src/u.ts', 'export const u = 1;\n');
    const res = await runCli(['test', '--dry-run', '--json'], root);
    expect(res.code).toBe(0);
    const data = res.json<{ label: string; data: { dryRun: boolean; runId: string; plannedCommands: Array<{ runner: string; command: string; args: string[] }>; events: unknown[]; selectionUsed: boolean; artifactsDir: string } }>().data;
    expect(res.json<{ label: string }>().label).toBe('NOT_RUN');
    expect(data.dryRun).toBe(true);
    expect(data.events).toEqual([]);
    expect(data.plannedCommands.length).toBeGreaterThanOrEqual(1);
    const vitest = data.plannedCommands.find((c) => c.runner === 'vitest');
    expect(vitest?.command).toBe('npx');
    expect(vitest?.args[0]).toBe('vitest');
    expect(data.selectionUsed).toBe(false); // not a git repo → whole suite
    expect(data.artifactsDir).toContain('.theqa');
  });

  it('rejects unknown policies with exit 2', async () => {
    const root = tmp();
    const res = await runCli(['test', '--policy', 'hourly', '--json'], root);
    expect(res.code).toBe(2);
    expect(res.json<{ data: { error: string } }>().data.error).toMatch(/unknown policy/);
  });
});
